# Generated by Django 3.2.3 on 2021-05-29 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('birthdate', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('token', models.CharField(default=None, max_length=500)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_response', models.IntegerField(default=None)),
                ('body', models.CharField(max_length=500)),
                ('images', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_api.post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(default=False)),
                ('aproved', models.BooleanField(default=True)),
                ('id_user_folloing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_folloing', to=settings.AUTH_USER_MODEL)),
                ('id_user_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user_followed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
